### ISSUE TITLE
Dependancy of msvcrt makes this a windows package

### ISSUE THREAD

**Issue by nicciniamh** [luanws/pymenu#1]
In trying to import, I get the following error (on macOS and Linux)

```
from pymenu import auto_menu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nicci/pyenv/lib/python3.11/site-packages/pymenu/__init__.py", line 1, in <module>
    from pymenu.menu import *
  File "/Users/nicci/pyenv/lib/python3.11/site-packages/pymenu/menu.py", line 10, in <module>
    from pymenu.utils import inputs
  File "/Users/nicci/pyenv/lib/python3.11/site-packages/pymenu/utils/inputs.py", line 1, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'
```

This pretty much makes this windows only.  Perhaps put that in the readme and on pypi. 
Thanks!

**Comment by luanws** [comment]
Unix support was added in version 0.2.1. Thanks for the sugestion.
